# Generated by Django 6.0.3 on 2026-03-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('checkin_lat', models.FloatField(blank=True, null=True)),
                ('checkin_lng', models.FloatField(blank=True, null=True)),
                ('checkin_image', models.ImageField(blank=True, null=True, upload_to='selfies/')),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_lat', models.FloatField(blank=True, null=True)),
                ('checkout_lng', models.FloatField(blank=True, null=True)),
                ('checkout_image', models.ImageField(blank=True, null=True, upload_to='selfies/')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-checkin_time'],
            },
        ),
    ]
